/**
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

/**
 * Representative Biography API
 *
 * Returns the pre-generated Wikipedia/Wikidata biography record for a single
 * member from `src/data/representative-biographies.json`.
 *
 * Why this route exists: the corpus is a 1.34 MB file covering all 520
 * members. `BiographyCard` is a client component, so importing the loader
 * there put the whole corpus in a browser chunk (~209 KB gzipped, plus a
 * 1.2 MB main-thread JSON.parse) to render one ~2 KB record. Reading it
 * server-side keeps the corpus in the server bundle — parsed once per lambda
 * instance and shared across every request that instance serves.
 *
 * A member absent from the corpus (newly seated, special election) returns
 * 404, which is the client's signal to fall back to the live Wikipedia and
 * Wikidata lookups it already implements.
 */

import { NextRequest, NextResponse } from 'next/server';
import logger from '@/lib/logging/simple-logger';
import { loadStaticBiography } from '@/lib/data/static-biographies';

// Bioguide IDs are one letter followed by six digits (e.g. S000033).
const BIOGUIDE_PATTERN = /^[A-Z]\d{6}$/;

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ bioguideId: string }> }
): Promise<NextResponse> {
  const { bioguideId } = await params;

  try {
    if (!bioguideId || !BIOGUIDE_PATTERN.test(bioguideId)) {
      return NextResponse.json({ error: 'Invalid bioguideId' }, { status: 400 });
    }

    const biography = await loadStaticBiography(bioguideId);

    if (!biography) {
      // Not an error — the caller falls back to live Wikipedia/Wikidata.
      return NextResponse.json(
        { error: 'No pre-generated biography for this member' },
        {
          status: 404,
          headers: {
            'Cache-Control': 'public, s-maxage=3600, stale-while-revalidate=86400',
          },
        }
      );
    }

    return NextResponse.json(
      { biography },
      {
        headers: {
          // The corpus is regenerated by scripts/generate-biography-data.mjs,
          // not on a live schedule — a long TTL is accurate here.
          'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=604800',
        },
      }
    );
  } catch (error) {
    logger.error('Representative biography API error', error as Error, { bioguideId });
    return NextResponse.json({ error: 'Failed to load biography' }, { status: 500 });
  }
}
