// Mock data for three federal officials across House/Senate, D/R.
// Numbers are illustrative; in production every datum carries a confidence + source.

const OFFICIAL_JEFFRIES = {
  id: 'jeffries',
  name: 'Hakeem S. Jeffries',
  short: 'Jeffries',
  role: 'U.S. Representative',
  chamber: 'House',
  district: 'NY-08',
  state: 'New York',
  party: 'd',
  partyLong: 'Democrat',
  position: 'House Minority Leader',
  since: 2013,
  next_election: 'Nov 3, 2026',
  congress: '119th',
  party_vote: 96,
  attendance: 98.4,
  bills_sponsored: 24,
  cosponsored: 312,
  committees: ['Budget', 'Judiciary'],
  caucus_count: 9,
  raised: '$3.42M',
  cash_on_hand: '$1.81M',
  small_donor_pct: 41,
  pac_pct: 27,
  industry_top: 'Securities & Investment',
  contact: {
    dc: {
      addr: '2433 Rayburn House Office Building, Washington, DC 20515',
      phone: '(202) 225-5936',
    },
    district: [
      {
        name: 'Brooklyn',
        addr: '55 Hanson Place, Suite 603, Brooklyn, NY 11217',
        phone: '(718) 237-2211',
      },
      {
        name: 'Queens',
        addr: '222-15 Linden Boulevard, Cambria Heights, NY 11411',
        phone: '(347) 305-3490',
      },
    ],
    web: 'jeffries.house.gov',
    contact_form: 'jeffries.house.gov/contact',
    twitter: '@RepJeffries',
  },
  sources: [
    { name: 'Congress.gov', id: '/member/J000294', updated: '2 days ago' },
    { name: 'FEC.gov', id: 'C00399001 · 2024', updated: 'Yesterday' },
    { name: 'House Clerk', id: 'roll-call-2024', updated: '5 hours ago' },
    { name: 'OpenSecrets', id: 'N00033640', updated: '1 week ago' },
    { name: 'Senate LDA', id: 'lobby-2024-q4', updated: '3 days ago' },
  ],
};

const OFFICIAL_MURKOWSKI = {
  id: 'murkowski',
  name: 'Lisa A. Murkowski',
  short: 'Murkowski',
  role: 'U.S. Senator',
  chamber: 'Senate',
  district: 'AK',
  state: 'Alaska',
  party: 'r',
  partyLong: 'Republican',
  position: 'Senior Senator',
  since: 2002,
  next_election: 'Nov 7, 2028',
  congress: '119th',
  party_vote: 71,
  attendance: 96.1,
  bills_sponsored: 38,
  cosponsored: 287,
  committees: ['Appropriations', 'Energy & Natural Resources', 'Indian Affairs', 'HELP'],
  caucus_count: 12,
  raised: '$8.91M',
  cash_on_hand: '$3.04M',
  small_donor_pct: 18,
  pac_pct: 44,
  industry_top: 'Oil & Gas',
  contact: {
    dc: { addr: '522 Hart Senate Office Building, Washington, DC 20510', phone: '(202) 224-6665' },
    district: [
      {
        name: 'Anchorage',
        addr: '510 L Street, Suite 600, Anchorage, AK 99501',
        phone: '(907) 271-3735',
      },
      {
        name: 'Fairbanks',
        addr: '101 12th Avenue, Suite 329, Fairbanks, AK 99701',
        phone: '(907) 456-0233',
      },
      {
        name: 'Juneau',
        addr: '800 Glacier Avenue, Suite 101, Juneau, AK 99801',
        phone: '(907) 586-7277',
      },
      {
        name: 'Ketchikan',
        addr: '1900 First Avenue, Suite 225, Ketchikan, AK 99901',
        phone: '(907) 225-6880',
      },
    ],
    web: 'murkowski.senate.gov',
    contact_form: 'murkowski.senate.gov/contact',
    twitter: '@lisamurkowski',
  },
  sources: [
    { name: 'Congress.gov', id: '/member/M001153', updated: '1 day ago' },
    { name: 'FEC.gov', id: 'S2AK00010 · 2022', updated: 'Yesterday' },
    { name: 'Senate Clerk', id: 'roll-call-2024', updated: '4 hours ago' },
    { name: 'OpenSecrets', id: 'N00026050', updated: '6 days ago' },
    { name: 'Senate LDA', id: 'lobby-2024-q4', updated: '2 days ago' },
  ],
};

const OFFICIAL_JOHNSON = {
  id: 'johnson',
  name: 'Mike Johnson',
  short: 'Johnson',
  role: 'U.S. Representative',
  chamber: 'House',
  district: 'LA-04',
  state: 'Louisiana',
  party: 'r',
  partyLong: 'Republican',
  position: 'Speaker of the House',
  since: 2017,
  next_election: 'Nov 3, 2026',
  congress: '119th',
  party_vote: 98,
  attendance: 94.7,
  bills_sponsored: 19,
  cosponsored: 198,
  committees: ['Armed Services', 'Judiciary'],
  caucus_count: 7,
  raised: '$15.20M',
  cash_on_hand: '$6.88M',
  small_donor_pct: 31,
  pac_pct: 38,
  industry_top: 'Leadership PACs',
  contact: {
    dc: { addr: 'H-232 The Capitol, Washington, DC 20515', phone: '(202) 225-2777' },
    district: [
      {
        name: 'Shreveport',
        addr: '6425 Youree Drive, Suite 350, Shreveport, LA 71105',
        phone: '(318) 798-2533',
      },
      {
        name: 'Leesville',
        addr: '444 Caspari Drive, South Hall 134, Leesville, LA 71446',
        phone: '(337) 423-8932',
      },
    ],
    web: 'mikejohnson.house.gov',
    contact_form: 'mikejohnson.house.gov/contact',
    twitter: '@SpeakerJohnson',
  },
  sources: [
    { name: 'Congress.gov', id: '/member/J000299', updated: '3 hours ago' },
    { name: 'FEC.gov', id: 'C00637657 · 2024', updated: 'Yesterday' },
    { name: 'House Clerk', id: 'roll-call-2024', updated: '6 hours ago' },
    { name: 'OpenSecrets', id: 'N00039106', updated: '4 days ago' },
    { name: 'Senate LDA', id: 'lobby-2024-q4', updated: '2 days ago' },
  ],
};

Object.assign(window, { OFFICIAL_JEFFRIES, OFFICIAL_MURKOWSKI, OFFICIAL_JOHNSON });
