/**
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

/**
 * Civic Brief Assembler
 *
 * Orchestrates data fetch → statistics → prompt → AI → fallback to produce
 * a single-page civic intelligence brief for any representative.
 *
 * Pattern: CivicAlignmentAnalyzer (cache check → parallel fetch → pre-compute → AI → fallback)
 */

import logger from '@/lib/logging/simple-logger';
import { getRedisCache } from '@/lib/cache/redis-client';
import { generateAIText } from '@/lib/ai/provider';
import { PLAIN_LANGUAGE_SYSTEM_PROMPT, PLAIN_LANGUAGE_RULES } from '@/lib/ai/plain-language';
import { getEnhancedRepresentative } from '@/features/representatives/services/congress.service';
import { getFECIdFromBioguide } from '@/lib/data/bioguide-fec-mapping';
import { fecApiService } from '@/lib/fec/fec-api-service';
import { aggregateByIndustrySector } from '@civiq/entity-resolution';
import {
  findCommitteeMapping,
  getCurrentElectionCycle,
  withTimeout,
  ANALYZER_TIMEOUT_MS,
} from './shared';
import { getJurisdictionSectorsForTopics } from '@/lib/connections/policy-area-map';
import { getTopicsForCommittee } from '@/lib/connections/committee-agency-map';
import { detectPatterns } from './civic-brief-patterns';
import type { PatternInput } from './civic-brief-patterns';
import type {
  CivicBriefInsight,
  BriefIdentity,
  BriefFunding,
  BriefVoting,
  BriefOversight,
  BriefPattern,
  FinanceJurisdictionInsight,
  InfluenceChainInsight,
} from '../types';
import type { IndustrySector } from '@/lib/fec/industry-taxonomy';

/** Redis cache TTL: 24 hours */
const CACHE_TTL = 24 * 60 * 60;

const DISCLAIMER =
  'This brief synthesizes public government data. Campaign contributions and lobbying ' +
  'are legal activities. Patterns do not indicate wrongdoing. Correlation does not imply causation.';

const METHODOLOGY =
  'Data assembled from Congress.gov, FEC.gov, and Senate LDA filings. ' +
  'Patterns detected via z-score and effect-size thresholds. ' +
  'Summary generated by AI using pre-computed statistics.';

/**
 * Generate a civic intelligence brief for a representative.
 * Returns cached result if fresh, otherwise computes from scratch.
 */
export async function assembleCivicBrief(bioguideId: string): Promise<CivicBriefInsight | null> {
  const cacheKey = `insight:civic_brief:${bioguideId}`;

  // 1. Check cache
  try {
    const cached = await getRedisCache().get<CivicBriefInsight>(cacheKey);
    if (cached) {
      logger.info('[CivicBrief] Cache hit', { bioguideId });
      return cached;
    }
  } catch {
    // Cache miss — continue
  }

  // 2-7. Fetch, compute, narrate, cache — all under timeout
  return withTimeout(computeAndCache(bioguideId, cacheKey), ANALYZER_TIMEOUT_MS, 'CivicBrief');
}

// ── Core Pipeline ────────────────────────────────────────────────────

async function computeAndCache(
  bioguideId: string,
  cacheKey: string
): Promise<CivicBriefInsight | null> {
  // 2. Fetch representative identity
  const rep = await getEnhancedRepresentative(bioguideId);
  if (!rep) {
    logger.warn('[CivicBrief] Representative not found', { bioguideId });
    return null;
  }

  const identity: BriefIdentity = {
    name: rep.name,
    party: rep.party,
    state: rep.state,
    district: rep.district ?? null,
    chamber: rep.chamber,
    termStart: rep.terms?.[0]?.startYear ?? 'Unknown',
    committees: (rep.committees ?? []).map(c => ({
      name: c.name,
      role: c.role ?? 'Member',
    })),
  };

  // 3. Parallel data fetch: FEC + existing intelligence endpoints
  const cycle = getCurrentElectionCycle();
  const fecId = getFECIdFromBioguide(bioguideId);

  const [fundingData, fjInsight, icInsight] = await Promise.all([
    fetchFundingData(fecId, cycle, identity),
    fetchCachedInsight<FinanceJurisdictionInsight>(`insight:finance_jurisdiction:${bioguideId}`),
    fetchCachedInsight<InfluenceChainInsight>(`insight:influence_chain:${bioguideId}`),
  ]);

  // 4. Assemble voting data from batch API
  const votingData = await fetchVotingData(bioguideId);

  // 5. Assemble oversight data
  const oversightData = assembleOversight(fjInsight, icInsight);

  // 6. Detect patterns
  const patternInput: PatternInput = {
    identity,
    funding: fundingData,
    voting: votingData,
    oversight: oversightData,
    // Peer stats — use defaults when not available from cached insights
    peerPartyAlignmentPct: null,
    peerPartyAlignmentStd: null,
    peerInStatePctMean: null,
    peerInStatePctStd: null,
  };

  const patterns = detectPatterns(patternInput);

  // 7. Generate AI summary or fallback
  const { summary, source } = await generateBriefSummary(
    identity,
    fundingData,
    votingData,
    oversightData,
    patterns
  );

  // Compute confidence based on data availability
  const confidence = computeConfidence(fundingData, votingData, oversightData);

  const brief: CivicBriefInsight = {
    bioguideId,
    identity,
    funding: fundingData,
    voting: votingData,
    oversight: oversightData,
    patterns,
    summary,
    confidence,
    dataAsOf: new Date().toISOString(),
    methodology: METHODOLOGY,
    disclaimer: DISCLAIMER,
    source,
    lastAnalyzedAt: new Date().toISOString(),
  };

  // 8. Cache result
  try {
    await getRedisCache().set(cacheKey, brief, CACHE_TTL);
    logger.info('[CivicBrief] Cached', { bioguideId, patterns: patterns.length, confidence });
  } catch {
    // Non-fatal cache write failure
  }

  return brief;
}

// ── Data Fetchers ────────────────────────────────────────────────────

async function fetchFundingData(
  fecId: string | null,
  cycle: number,
  identity: BriefIdentity
): Promise<BriefFunding> {
  const empty: BriefFunding = {
    totalRaised: null,
    totalSpent: null,
    cashOnHand: null,
    inStatePct: null,
    topSectors: [],
    contributionsSampled: 0,
    cycle,
  };

  if (!fecId) return empty;

  try {
    const [summary, contributions] = await Promise.all([
      fecApiService.getFinancialSummary(fecId, cycle).catch(() => null),
      fecApiService.getSampleContributions(fecId, cycle, 200).catch(() => []),
    ]);

    const totalRaised = summary?.receipts ?? summary?.total_receipts ?? null;
    const totalSpent = summary?.disbursements ?? summary?.total_disbursements ?? null;
    const cashOnHand =
      summary?.last_cash_on_hand_end_period ?? summary?.cash_on_hand_end_period ?? null;

    // Compute in-state percentage
    let inStatePct: number | null = null;
    if (contributions.length > 0) {
      const inState = contributions.filter(c => c.contributor_state === identity.state);
      inStatePct = (inState.length / contributions.length) * 100;
    }

    // Aggregate by sector
    const sectorAgg = aggregateByIndustrySector(contributions);

    // Determine which sectors overlap with committee jurisdiction
    const jurisdictionSectors = new Set<IndustrySector>();
    for (const committee of identity.committees) {
      const mapping = findCommitteeMapping(committee.name);
      if (mapping) {
        const topics = getTopicsForCommittee(mapping.committeeName);
        const sectors = getJurisdictionSectorsForTopics(topics);
        for (const s of sectors) jurisdictionSectors.add(s);
      }
    }

    const topSectors = sectorAgg
      .sort((a, b) => b.totalAmount - a.totalAmount)
      .slice(0, 5)
      .map(s => ({
        sector: s.sector,
        amount: Math.round(s.totalAmount),
        pct: s.percentage,
        overlapsCommittee: jurisdictionSectors.has(s.sector),
      }));

    return {
      totalRaised,
      totalSpent,
      cashOnHand,
      inStatePct,
      topSectors,
      contributionsSampled: contributions.length,
      cycle,
    };
  } catch (error) {
    logger.warn('[CivicBrief] FEC data fetch failed', { fecId, error: (error as Error).message });
    return empty;
  }
}

async function fetchVotingData(bioguideId: string): Promise<BriefVoting> {
  try {
    const response = await fetch(
      `${process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'}/api/representative/${bioguideId}/batch`,
      { next: { revalidate: 3600 } }
    );

    if (!response.ok) {
      return {
        totalVotes: 0,
        partyAlignmentPct: null,
        missedVotePct: null,
        billsSponsored: 0,
        billsCosponsored: 0,
      };
    }

    const batch = await response.json();
    const data = batch?.data ?? {};

    const votes = data.votes;
    const bills = data.bills;

    return {
      totalVotes: Array.isArray(votes) ? votes.length : 0,
      partyAlignmentPct: null, // Computed by temporal analyzer, not in batch
      missedVotePct: null,
      billsSponsored: bills?.sponsored?.count ?? 0,
      billsCosponsored: bills?.cosponsored?.count ?? 0,
    };
  } catch {
    return {
      totalVotes: 0,
      partyAlignmentPct: null,
      missedVotePct: null,
      billsSponsored: 0,
      billsCosponsored: 0,
    };
  }
}

async function fetchCachedInsight<T>(cacheKey: string): Promise<T | null> {
  try {
    return await getRedisCache().get<T>(cacheKey);
  } catch {
    return null;
  }
}

function assembleOversight(
  fjInsight: FinanceJurisdictionInsight | null,
  icInsight: InfluenceChainInsight | null
): BriefOversight {
  const topMatches: BriefOversight['topLobbyingMatches'] = [];

  if (icInsight?.chains) {
    for (const chain of icInsight.chains.slice(0, 3)) {
      topMatches.push({
        filing: chain.organization,
        bill: chain.billTitle,
        similarity: chain.textSimilarity ?? 0,
      });
    }
  }

  return {
    jurisdictionOverlapScore: fjInsight?.overlapScore ?? null,
    lobbyingAlignmentScore:
      icInsight && icInsight.chains.length > 0
        ? icInsight.chains.reduce((sum, c) => sum + c.chainConfidence, 0) / icInsight.chains.length
        : null,
    topLobbyingMatches: topMatches,
  };
}

// ── AI Summary Generation ────────────────────────────────────────────

async function generateBriefSummary(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight,
  patterns: BriefPattern[]
): Promise<{ summary: string; source: 'ai-generated' | 'statistical-fallback' }> {
  const fallbackSummary = buildFallbackSummary(identity, funding, voting, patterns);

  try {
    const systemPrompt =
      `You write civic intelligence briefs for CIV.IQ, a nonpartisan platform that helps citizens understand their elected representatives. Your audience is everyday voters, not policy analysts. Write the way a local newspaper reporter would explain things to a neighbor. ` +
      PLAIN_LANGUAGE_SYSTEM_PROMPT;

    const userPrompt = buildAIPrompt(identity, funding, voting, oversight, patterns);

    const response = await generateAIText(systemPrompt, userPrompt, {
      temperature: 0.3,
      maxTokens: 2000,
    });

    if (!response) return { summary: fallbackSummary, source: 'statistical-fallback' };

    // Parse JSON response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return { summary: fallbackSummary, source: 'statistical-fallback' };

    const parsed = JSON.parse(jsonMatch[0]);
    const aiSummary = parsed.summary;

    if (typeof aiSummary === 'string' && aiSummary.length > 20) {
      // Also update pattern narratives from AI if provided
      if (Array.isArray(parsed.patterns)) {
        for (const aiPattern of parsed.patterns) {
          const match = patterns.find(p => p.type === aiPattern.type);
          if (match && typeof aiPattern.headline === 'string') {
            match.headline = aiPattern.headline;
          }
          if (match && typeof aiPattern.detail === 'string') {
            match.detail = aiPattern.detail;
          }
        }
      }
      return { summary: aiSummary, source: 'ai-generated' };
    }

    return { summary: fallbackSummary, source: 'statistical-fallback' };
  } catch (error) {
    logger.warn('[CivicBrief] AI summary failed, using fallback', {
      error: (error as Error).message,
    });
    return { summary: fallbackSummary, source: 'statistical-fallback' };
  }
}

function buildAIPrompt(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight,
  patterns: BriefPattern[]
): string {
  const committeeList =
    identity.committees.map(c => `${c.name} (${c.role})`).join(', ') || 'None listed';

  const sectorLines =
    funding.topSectors
      .map(
        s =>
          `- ${s.sector}: $${s.amount.toLocaleString()} (${s.pct.toFixed(1)}%)${s.overlapsCommittee ? ' [committee jurisdiction]' : ''}`
      )
      .join('\n') || 'No sector data';

  const patternLines =
    patterns
      .map(p => `[${p.type}]: ${p.headline}\nData: ${JSON.stringify(p.dataPoints)}`)
      .join('\n\n') || 'No significant patterns detected';

  const lobbyingLines =
    oversight.topLobbyingMatches
      .map(m => `- "${m.filing}" ↔ "${m.bill}" (${(m.similarity * 100).toFixed(0)}% similarity)`)
      .join('\n') || 'None';

  return `Representative: ${identity.name}, ${identity.party}-${identity.state}, ${identity.chamber}
Term: ${identity.termStart} - present
Committees: ${committeeList}

FUNDING (cycle ${funding.cycle}):
Total raised: ${funding.totalRaised !== null ? '$' + funding.totalRaised.toLocaleString() : 'N/A'}
Total spent: ${funding.totalSpent !== null ? '$' + funding.totalSpent.toLocaleString() : 'N/A'}
Cash on hand: ${funding.cashOnHand !== null ? '$' + funding.cashOnHand.toLocaleString() : 'N/A'}
In-state: ${funding.inStatePct !== null ? funding.inStatePct.toFixed(1) + '%' : 'N/A'}
Top sectors:
${sectorLines}
Contributions sampled: ${funding.contributionsSampled}

VOTING:
Total votes: ${voting.totalVotes}
Party alignment: ${voting.partyAlignmentPct !== null ? voting.partyAlignmentPct.toFixed(1) + '%' : 'N/A'}
Bills sponsored: ${voting.billsSponsored} | Cosponsored: ${voting.billsCosponsored}

OVERSIGHT:
Jurisdiction overlap: ${oversight.jurisdictionOverlapScore !== null ? (oversight.jurisdictionOverlapScore * 100).toFixed(1) + '%' : 'N/A'}
Lobbying alignment: ${oversight.lobbyingAlignmentScore !== null ? (oversight.lobbyingAlignmentScore * 100).toFixed(1) + '%' : 'N/A'}
Top lobbying matches:
${lobbyingLines}

DETECTED PATTERNS (select 3-5 most noteworthy, narrate each):
${patternLines}

Generate JSON with these fields only:
{
  "patterns": [{ "type": "pattern-type", "headline": "1 sentence a citizen can understand", "detail": "2-3 sentences explaining what the numbers mean for voters" }],
  "summary": "2-3 sentence overview a voter can read in 15 seconds. Lead with what matters most. Use 'your representative' where natural."
}

${PLAIN_LANGUAGE_RULES}
- Write for voters, not policy analysts. Explain what the numbers mean, not just what they are.
- State only what the data shows. Do not speculate on motives.
- Do not say a legislator "should" do anything.
- Each statement must reference specific numbers from the data above.
- Use "pattern", "correlation", "association" — never "caused", "influenced", "resulted in".
- Refer to the representative by last name after the first mention.`;
}

function buildFallbackSummary(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  patterns: BriefPattern[]
): string {
  const partyName =
    identity.party === 'D'
      ? 'Democrat'
      : identity.party === 'R'
        ? 'Republican'
        : identity.party === 'I' || identity.party === 'ID'
          ? 'Independent'
          : identity.party;
  const location = identity.district
    ? `${identity.state}'s ${ordinal(parseInt(identity.district))} congressional district`
    : identity.state;

  const parts: string[] = [];

  parts.push(
    `${identity.name} is a ${partyName} who represents ${location} in the ${identity.chamber}.`
  );

  if (funding.totalRaised !== null && voting.totalVotes > 0) {
    parts.push(
      `They have raised $${formatCompactFallback(funding.totalRaised)} for the ${funding.cycle} election cycle and cast ${voting.totalVotes} recorded votes so far.`
    );
  } else if (funding.totalRaised !== null) {
    parts.push(
      `They have raised $${formatCompactFallback(funding.totalRaised)} for the ${funding.cycle} election cycle.`
    );
  } else if (voting.totalVotes > 0) {
    parts.push(`They have cast ${voting.totalVotes} recorded votes so far.`);
  }

  if (patterns.length > 0) {
    parts.push(patterns[0]!.headline);
  }

  return parts.join(' ');
}

function ordinal(n: number): string {
  if (!Number.isFinite(n) || n <= 0) return String(n);
  const suffixes = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (suffixes[(v - 20) % 10] ?? suffixes[v] ?? suffixes[0]!);
}

function formatCompactFallback(amount: number): string {
  if (amount >= 1_000_000) return `${(amount / 1_000_000).toFixed(1)} million`;
  if (amount >= 1_000) return amount.toLocaleString();
  return amount.toLocaleString();
}

// ── Confidence Computation ───────────────────────────────────────────

function computeConfidence(
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight
): number {
  let score = 0;
  let maxScore = 0;

  // Funding data available?
  maxScore += 3;
  if (funding.totalRaised !== null) score += 1;
  if (funding.contributionsSampled >= 50) score += 1;
  if (funding.topSectors.length >= 3) score += 1;

  // Voting data available?
  maxScore += 2;
  if (voting.totalVotes >= 10) score += 1;
  if (voting.billsSponsored > 0) score += 1;

  // Oversight data available?
  maxScore += 2;
  if (oversight.jurisdictionOverlapScore !== null) score += 1;
  if (oversight.topLobbyingMatches.length > 0) score += 1;

  return Math.round((score / maxScore) * 100) / 100;
}
