/**
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

/**
 * Civic Brief Assembler
 *
 * Orchestrates data fetch → statistics → prompt → AI → fallback to produce
 * a single-page civic intelligence brief for any representative.
 *
 * Pattern: CivicAlignmentAnalyzer (cache check → parallel fetch → pre-compute → AI → fallback)
 */

import logger from '@/lib/logging/simple-logger';
import { getRedisCache } from '@/lib/cache/redis-client';
import { generateAIText } from '@/lib/ai/provider';
import { PLAIN_LANGUAGE_SYSTEM_PROMPT, PLAIN_LANGUAGE_RULES } from '@/lib/ai/plain-language';
import { getEnhancedRepresentative } from '@/features/representatives/services/congress.service';
import { batchVotingService } from '@/features/representatives/services/batch-voting-service';
import {
  getBillsSummary,
  getComprehensiveBillsByMember,
} from '@/services/congress/optimized-congress.service';
import { getFECIdFromBioguide } from '@/lib/data/bioguide-fec-mapping';
import { fecApiService } from '@/lib/fec/fec-api-service';
import { aggregateByIndustrySector } from '@civiq/entity-resolution';
import {
  findCommitteeMapping,
  freshestDate,
  getCurrentElectionCycle,
  withTimeout,
  ANALYZER_TIMEOUT_MS,
  trackInsightCacheHit,
  withInsightTracking,
  classifySignal,
  SourceCollector,
} from './shared';
import { mean, sampleStandardDeviation } from '../statistics/civic-stats';
import { getJurisdictionSectorsForTopics } from '@/lib/connections/policy-area-map';
import { getTopicsForCommittee } from '@/lib/connections/committee-agency-map';
import { detectPatterns } from './civic-brief-patterns';
import type { PatternInput } from './civic-brief-patterns';
import type {
  CivicBriefInsight,
  BriefIdentity,
  BriefFunding,
  BriefVoting,
  BriefOversight,
  BriefPattern,
  FinanceJurisdictionInsight,
  InfluenceChainInsight,
  TemporalVoteInsight,
} from '../types';
import type { IndustrySector } from '@/lib/fec/industry-taxonomy';

/** Redis cache TTL: 24 hours */
const CACHE_TTL = 24 * 60 * 60;

const DISCLAIMER =
  'This brief synthesizes public government data. Campaign contributions and lobbying ' +
  'are legal activities. Patterns do not indicate wrongdoing. Correlation does not imply causation.';

const METHODOLOGY =
  'Data assembled from Congress.gov, FEC.gov, and Senate LDA filings. ' +
  'Patterns detected via z-score and effect-size thresholds. ' +
  'Summary generated by AI using pre-computed statistics.';

/**
 * Generate a civic intelligence brief for a representative.
 * Returns cached result if fresh, otherwise computes from scratch.
 */
export async function assembleCivicBrief(bioguideId: string): Promise<CivicBriefInsight | null> {
  const cacheKey = `insight:civic_brief:${bioguideId}`;

  // 1. Check cache
  try {
    const cached = await getRedisCache().get<CivicBriefInsight>(cacheKey);
    if (cached) {
      logger.info('[CivicBrief] Cache hit', { bioguideId });
      trackInsightCacheHit('civic-brief');
      return cached;
    }
  } catch {
    // Cache miss — continue
  }

  // 2-7. Fetch, compute, narrate, cache — all under timeout
  return withInsightTracking('civic-brief', () =>
    withTimeout(computeAndCache(bioguideId, cacheKey), ANALYZER_TIMEOUT_MS, 'CivicBrief')
  );
}

// ── Core Pipeline ────────────────────────────────────────────────────

async function computeAndCache(
  bioguideId: string,
  cacheKey: string
): Promise<CivicBriefInsight | null> {
  // 2. Fetch representative identity
  const rep = await getEnhancedRepresentative(bioguideId);
  if (!rep) {
    logger.warn('[CivicBrief] Representative not found', { bioguideId });
    return null;
  }

  const identity: BriefIdentity = {
    name: rep.name,
    party: rep.party,
    state: rep.state,
    district: rep.district ?? null,
    chamber: rep.chamber,
    termStart: rep.terms?.[0]?.startYear ?? 'Unknown',
    committees: (rep.committees ?? []).map(c => ({
      name: c.name,
      role: c.role ?? 'Member',
    })),
  };

  // 3. Parallel data fetch: FEC + existing intelligence endpoints
  const cycle = getCurrentElectionCycle();
  const fecId = getFECIdFromBioguide(bioguideId);

  const [fundingData, fjInsight, icInsight, temporalInsight] = await Promise.all([
    fetchFundingData(fecId, cycle, identity),
    fetchCachedInsight<FinanceJurisdictionInsight>(`insight:finance_jurisdiction:${bioguideId}`),
    fetchCachedInsight<InfluenceChainInsight>(`insight:influence_chain:${bioguideId}`),
    fetchCachedInsight<TemporalVoteInsight>(`insight:temporal_votes:${bioguideId}`),
  ]);

  // 4. Assemble voting data via direct service call
  const votingData = await fetchVotingData(bioguideId, rep.chamber as 'House' | 'Senate');

  // Enrich partyAlignmentPct from temporal insight if available
  if (votingData.partyAlignmentPct === null && temporalInsight?.quarters?.length) {
    const avgAlignment = mean(temporalInsight.quarters.map(q => q.alignmentScore)) * 100;
    votingData.partyAlignmentPct = Math.round(avgAlignment * 10) / 10;
  }

  // Cache in-state pct for peer aggregation (fire-and-forget)
  if (fundingData.inStatePct !== null) {
    cacheInStatePctScore(bioguideId, rep.chamber, fundingData.inStatePct);
  }

  // 5. Assemble oversight data
  const oversightData = assembleOversight(fjInsight, icInsight);

  // 6. Fetch peer stats in parallel
  const [peerPartyStats, peerInStateStats] = await Promise.all([
    fetchPeerPartyAlignmentStats(bioguideId, rep.chamber, rep.party),
    fetchPeerInStatePctStats(bioguideId, rep.chamber),
  ]);

  // 7. Detect patterns
  const patternInput: PatternInput = {
    identity,
    funding: fundingData,
    voting: votingData,
    oversight: oversightData,
    peerPartyAlignmentPct: peerPartyStats?.mean ?? null,
    peerPartyAlignmentStd: peerPartyStats?.std ?? null,
    peerInStatePctMean: peerInStateStats?.mean ?? null,
    peerInStatePctStd: peerInStateStats?.std ?? null,
    bioguideId,
    fecId: fecId ?? null,
  };

  const patterns = detectPatterns(patternInput);

  // 8. Generate AI summary or fallback
  const { summary, source } = await generateBriefSummary(
    identity,
    fundingData,
    votingData,
    oversightData,
    patterns
  );

  // Compute confidence based on data availability
  const confidence = computeConfidence(fundingData, votingData, oversightData);

  const sc = new SourceCollector();
  sc.add('Congress.gov', '119th Congress');
  sc.add('FEC individual filings', `${getCurrentElectionCycle()} cycle`);
  if (icInsight) sc.add('Senate LDA filings', '119th Congress');

  const brief: CivicBriefInsight = {
    bioguideId,
    identity,
    funding: fundingData,
    voting: votingData,
    oversight: oversightData,
    patterns,
    summary,
    confidence,
    confidenceMethod: 'computed',
    dataAsOf: freshestDate(fjInsight?.dataAsOf, icInsight?.dataAsOf),
    methodology: METHODOLOGY,
    disclaimer: DISCLAIMER,
    signal: classifySignal({
      confidence,
      hasAnomaly: patterns.some(p => p.significance >= 0.8),
    }),
    sources: sc.toSources(),
    source,
    lastAnalyzedAt: new Date().toISOString(),
  };

  // 8. Cache result
  try {
    await getRedisCache().set(cacheKey, brief, CACHE_TTL);
    logger.info('[CivicBrief] Cached', { bioguideId, patterns: patterns.length, confidence });
  } catch {
    // Non-fatal cache write failure
  }

  return brief;
}

// ── Data Fetchers ────────────────────────────────────────────────────

async function fetchFundingData(
  fecId: string | null,
  cycle: number,
  identity: BriefIdentity
): Promise<BriefFunding> {
  const empty: BriefFunding = {
    totalRaised: null,
    totalSpent: null,
    cashOnHand: null,
    inStatePct: null,
    topSectors: [],
    contributionsSampled: 0,
    cycle,
  };

  if (!fecId) return empty;

  try {
    const [summary, contributions] = await Promise.all([
      fecApiService.getFinancialSummary(fecId, cycle).catch(() => null),
      fecApiService.getSampleContributions(fecId, cycle, 500).catch(() => []),
    ]);

    const totalRaised = summary?.receipts ?? summary?.total_receipts ?? null;
    const totalSpent = summary?.disbursements ?? summary?.total_disbursements ?? null;
    const cashOnHand =
      summary?.last_cash_on_hand_end_period ?? summary?.cash_on_hand_end_period ?? null;

    // Compute in-state percentage
    let inStatePct: number | null = null;
    if (contributions.length > 0) {
      const inState = contributions.filter(c => c.contributor_state === identity.state);
      inStatePct = (inState.length / contributions.length) * 100;
    }

    // Aggregate by sector
    const sectorAgg = aggregateByIndustrySector(contributions);

    // Determine which sectors overlap with committee jurisdiction
    const jurisdictionSectors = new Set<IndustrySector>();
    for (const committee of identity.committees) {
      const mapping = findCommitteeMapping(committee.name);
      if (mapping) {
        const topics = getTopicsForCommittee(mapping.committeeName);
        const sectors = getJurisdictionSectorsForTopics(topics);
        for (const s of sectors) jurisdictionSectors.add(s);
      }
    }

    const topSectors = sectorAgg
      .sort((a, b) => b.totalAmount - a.totalAmount)
      .slice(0, 5)
      .map(s => ({
        sector: s.sector,
        amount: Math.round(s.totalAmount),
        pct: s.percentage,
        overlapsCommittee: jurisdictionSectors.has(s.sector),
      }));

    return {
      totalRaised,
      totalSpent,
      cashOnHand,
      inStatePct,
      topSectors,
      contributionsSampled: contributions.length,
      cycle,
    };
  } catch (error) {
    logger.warn('[CivicBrief] FEC data fetch failed', { fecId, error: (error as Error).message });
    return empty;
  }
}

async function fetchVotingData(
  bioguideId: string,
  chamber: 'House' | 'Senate'
): Promise<BriefVoting> {
  const empty: BriefVoting = {
    totalVotes: 0,
    partyAlignmentPct: null,
    missedVotePct: null,
    billsSponsored: 0,
    billsCosponsored: 0,
  };

  try {
    // Fetch votes and bill sponsorship counts in parallel
    const [votes, billsSummary] = await Promise.all([
      chamber === 'House'
        ? batchVotingService.getHouseMemberVotes(bioguideId, 119, undefined, 200)
        : batchVotingService.getSenateMemberVotes(bioguideId, 119, undefined, 200),
      getBillsSummary(bioguideId).catch(() => null),
    ]);

    // Compute missed vote percentage from "Not Voting" positions
    let missedVotePct: number | null = null;
    if (votes.length > 0) {
      const notVotingCount = votes.filter(v => v.position === 'Not Voting').length;
      missedVotePct = (notVotingCount / votes.length) * 100;
    }

    // Count bills that progressed past introduction
    let billsProgressed: number | undefined;
    const sponsoredCount = billsSummary?.currentCongress.count ?? 0;
    if (sponsoredCount > 0) {
      try {
        const billsResponse = await getComprehensiveBillsByMember({
          bioguideId,
          limit: 50,
          congress: 119,
        });
        const progressedStatuses =
          /passed|reported|enacted|signed|became law|ordered to be reported/i;
        billsProgressed = billsResponse.bills.filter(
          b => b.relationship === 'sponsored' && progressedStatuses.test(b.lastAction)
        ).length;
      } catch {
        // Non-fatal — billsProgressed remains undefined
      }
    }

    return {
      totalVotes: votes.length,
      partyAlignmentPct: null, // Enriched from temporal analyzer cache
      missedVotePct,
      billsSponsored: sponsoredCount,
      billsCosponsored: billsSummary?.cosponsoredCount ?? 0,
      billsProgressed,
    };
  } catch (error) {
    logger.warn('[CivicBrief] Vote fetch failed', {
      bioguideId,
      error: (error as Error).message,
    });
    return empty;
  }
}

async function fetchCachedInsight<T>(cacheKey: string): Promise<T | null> {
  try {
    return await getRedisCache().get<T>(cacheKey);
  } catch {
    return null;
  }
}

/** Cache in-state funding percentage for peer aggregation. */
function cacheInStatePctScore(bioguideId: string, chamber: string, inStatePct: number): void {
  getRedisCache()
    .set(`brief-instate-pct:${chamber}:${bioguideId}`, inStatePct, 24 * 60 * 60)
    .catch(() => {
      /* non-fatal */
    });
}

interface PeerStats {
  mean: number;
  std: number;
}

const MIN_PEER_COUNT = 5;

/** Baseline party alignment stats derived from well-established congressional norms. */
const BASELINE_PARTY_ALIGNMENT: Record<string, PeerStats> = {
  Senate: { mean: 91.5, std: 5.2 },
  House: { mean: 93.5, std: 4.3 },
};

/** Baseline in-state funding stats derived from congressional norms. */
const BASELINE_IN_STATE_PCT: Record<string, PeerStats> = {
  Senate: { mean: 35, std: 12 },
  House: { mean: 55, std: 15 },
};

/** Fetch peer party alignment stats from cached temporal alignment scores. */
async function fetchPeerPartyAlignmentStats(
  bioguideId: string,
  chamber: string,
  party: string
): Promise<PeerStats | null> {
  try {
    const pattern = `temporal-alignment-party:${chamber}:${party}:*`;
    const keys = await getRedisCache().keys(pattern);
    const peerKeys = keys.filter(k => !k.endsWith(`:${bioguideId}`));

    if (peerKeys.length >= MIN_PEER_COUNT) {
      const values = await getRedisCache().mget<number>(peerKeys);
      const scores = values
        .filter((v): v is number => v !== null && typeof v === 'number')
        .map(v => v * 100);

      if (scores.length >= MIN_PEER_COUNT) {
        return {
          mean: mean(scores),
          std: sampleStandardDeviation(scores),
        };
      }
    }

    // Fall back to baseline when insufficient peers cached
    return BASELINE_PARTY_ALIGNMENT[chamber] ?? null;
  } catch {
    return BASELINE_PARTY_ALIGNMENT[chamber] ?? null;
  }
}

/** Fetch peer in-state funding percentage stats from cached values. */
async function fetchPeerInStatePctStats(
  bioguideId: string,
  chamber: string
): Promise<PeerStats | null> {
  try {
    const pattern = `brief-instate-pct:${chamber}:*`;
    const keys = await getRedisCache().keys(pattern);
    const peerKeys = keys.filter(k => !k.endsWith(`:${bioguideId}`));

    if (peerKeys.length >= MIN_PEER_COUNT) {
      const values = await getRedisCache().mget<number>(peerKeys);
      const scores = values.filter((v): v is number => v !== null && typeof v === 'number');

      if (scores.length >= MIN_PEER_COUNT) {
        return {
          mean: mean(scores),
          std: sampleStandardDeviation(scores),
        };
      }
    }

    // Fall back to baseline when insufficient peers cached
    return BASELINE_IN_STATE_PCT[chamber] ?? null;
  } catch {
    return BASELINE_IN_STATE_PCT[chamber] ?? null;
  }
}

function assembleOversight(
  fjInsight: FinanceJurisdictionInsight | null,
  icInsight: InfluenceChainInsight | null
): BriefOversight {
  const topMatches: BriefOversight['topLobbyingMatches'] = [];

  if (icInsight?.chains) {
    for (const chain of icInsight.chains.slice(0, 3)) {
      topMatches.push({
        filing: chain.organization,
        bill: chain.billTitle,
        similarity: chain.textSimilarity ?? 0,
      });
    }
  }

  return {
    jurisdictionOverlapScore: fjInsight?.overlapScore ?? null,
    lobbyingAlignmentScore:
      icInsight && icInsight.chains.length > 0
        ? icInsight.chains.reduce((sum, c) => sum + c.chainConfidence, 0) / icInsight.chains.length
        : null,
    topLobbyingMatches: topMatches,
  };
}

// ── AI Summary Generation ────────────────────────────────────────────

async function generateBriefSummary(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight,
  patterns: BriefPattern[]
): Promise<{ summary: string; source: 'ai-generated' | 'statistical-fallback' }> {
  const fallbackSummary = buildFallbackSummary(identity, funding, voting, patterns);

  try {
    const systemPrompt =
      `You write civic intelligence briefs for CIV.IQ, a nonpartisan platform that helps citizens understand their elected representatives. Your audience is everyday voters, not policy analysts. Write the way a local newspaper reporter would explain things to a neighbor. ` +
      PLAIN_LANGUAGE_SYSTEM_PROMPT;

    const userPrompt = buildAIPrompt(identity, funding, voting, oversight, patterns);

    const response = await generateAIText(systemPrompt, userPrompt, {
      temperature: 0.3,
      maxTokens: 2000,
    });

    if (!response) return { summary: fallbackSummary, source: 'statistical-fallback' };

    // Parse JSON response
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return { summary: fallbackSummary, source: 'statistical-fallback' };

    const parsed = JSON.parse(jsonMatch[0]);
    const aiSummary = parsed.summary;

    if (typeof aiSummary === 'string' && aiSummary.length > 20) {
      // Also update pattern narratives from AI if provided
      if (Array.isArray(parsed.patterns)) {
        for (const aiPattern of parsed.patterns) {
          const match = patterns.find(p => p.type === aiPattern.type);
          if (match && typeof aiPattern.headline === 'string') {
            match.headline = aiPattern.headline;
          }
          if (match && typeof aiPattern.detail === 'string') {
            match.detail = aiPattern.detail;
          }
        }
      }
      return { summary: aiSummary, source: 'ai-generated' };
    }

    return { summary: fallbackSummary, source: 'statistical-fallback' };
  } catch (error) {
    logger.warn('[CivicBrief] AI summary failed, using fallback', {
      error: (error as Error).message,
    });
    return { summary: fallbackSummary, source: 'statistical-fallback' };
  }
}

function buildAIPrompt(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight,
  patterns: BriefPattern[]
): string {
  const committeeList =
    identity.committees.map(c => `${c.name} (${c.role})`).join(', ') || 'None listed';

  const sectorLines =
    funding.topSectors
      .map(
        s =>
          `- ${s.sector}: $${s.amount.toLocaleString()} (${s.pct.toFixed(1)}%)${s.overlapsCommittee ? ' [committee jurisdiction]' : ''}`
      )
      .join('\n') || 'No sector data';

  const patternLines =
    patterns
      .map(p => `[${p.type}]: ${p.headline}\nData: ${JSON.stringify(p.dataPoints)}`)
      .join('\n\n') || 'No significant patterns detected';

  const lobbyingLines =
    oversight.topLobbyingMatches
      .map(m => `- "${m.filing}" ↔ "${m.bill}" (${(m.similarity * 100).toFixed(0)}% similarity)`)
      .join('\n') || 'None';

  return `Representative: ${identity.name}, ${identity.party}-${identity.state}, ${identity.chamber}
Term: ${identity.termStart} - present
Committees: ${committeeList}

FUNDING (cycle ${funding.cycle}):
Total raised: ${funding.totalRaised !== null ? '$' + funding.totalRaised.toLocaleString() : 'N/A'}
Total spent: ${funding.totalSpent !== null ? '$' + funding.totalSpent.toLocaleString() : 'N/A'}
Cash on hand: ${funding.cashOnHand !== null ? '$' + funding.cashOnHand.toLocaleString() : 'N/A'}
In-state: ${funding.inStatePct !== null ? funding.inStatePct.toFixed(1) + '%' : 'N/A'}
Top sectors:
${sectorLines}
Contributions sampled: ${funding.contributionsSampled}

VOTING:
Total votes: ${voting.totalVotes}
Party alignment: ${voting.partyAlignmentPct !== null ? voting.partyAlignmentPct.toFixed(1) + '%' : 'N/A'}
Bills sponsored: ${voting.billsSponsored} | Cosponsored: ${voting.billsCosponsored}

OVERSIGHT:
Jurisdiction overlap: ${oversight.jurisdictionOverlapScore !== null ? (oversight.jurisdictionOverlapScore * 100).toFixed(1) + '%' : 'N/A'}
Lobbying alignment: ${oversight.lobbyingAlignmentScore !== null ? (oversight.lobbyingAlignmentScore * 100).toFixed(1) + '%' : 'N/A'}
Top lobbying matches:
${lobbyingLines}

DETECTED PATTERNS (select 3-5 most noteworthy, narrate each):
${patternLines}

Generate JSON with these fields only:
{
  "patterns": [{ "type": "pattern-type", "headline": "1 plain sentence — answer: why should a voter care?", "detail": "2-3 sentences. Explain what the numbers mean for the voter, not just what they are. Start with the most important fact." }],
  "summary": "2-3 sentences a voter can read in 15 seconds. Start with 'Your representative' and say something useful about who funds them and what they do. End with the single most important finding."
}

${PLAIN_LANGUAGE_RULES}
- Write for voters, not policy analysts. Answer the question: "So what? Why does this matter to me?"
- Do NOT just restate numbers. Explain what they mean. "$2.5M raised" is a fact. "Most of that money came from the banking industry, which their committee regulates" is an insight.
- Use "you" and "your" to address the reader. Say "your representative" not "the representative."
- State only what the data shows. Do not speculate on motives.
- Do not say a legislator "should" do anything.
- Use "pattern", "correlation", "association" — never "caused", "influenced", "resulted in".
- Use the representative's last name after the first mention.
- Explain terms: "cosponsored" means "signed on to support someone else's bill." "Committee jurisdiction" means "the topics that committee is in charge of."`;
}

function buildFallbackSummary(
  identity: BriefIdentity,
  funding: BriefFunding,
  voting: BriefVoting,
  patterns: BriefPattern[]
): string {
  const partyName =
    identity.party === 'D'
      ? 'Democrat'
      : identity.party === 'R'
        ? 'Republican'
        : identity.party === 'I' || identity.party === 'ID'
          ? 'Independent'
          : identity.party;

  const last = identity.name.split(' ').pop() ?? identity.name;

  // Lead with who they are and where
  const location = identity.district
    ? `${identity.state}'s ${ordinal(parseInt(identity.district))} district`
    : identity.state;

  const parts: string[] = [];

  parts.push(
    `Your representative ${identity.name} is a ${partyName} serving ${location} in the U.S. ${identity.chamber}.`
  );

  // Tell the citizen something useful — money and activity
  if (funding.totalRaised !== null && voting.totalVotes > 0) {
    parts.push(
      `${last} has raised $${formatCompactFallback(funding.totalRaised)} for the ${funding.cycle} election cycle and cast ${voting.totalVotes} votes on the record.`
    );
  } else if (funding.totalRaised !== null) {
    parts.push(
      `${last} has raised $${formatCompactFallback(funding.totalRaised)} for the ${funding.cycle} election cycle.`
    );
  } else if (voting.totalVotes > 0) {
    parts.push(`${last} has cast ${voting.totalVotes} votes on the record so far this session.`);
  }

  // Add the most noteworthy finding — this is what makes it an intelligence brief, not a bio
  if (patterns.length > 0) {
    parts.push(patterns[0]!.headline);
  }

  return parts.join(' ');
}

function ordinal(n: number): string {
  if (!Number.isFinite(n) || n <= 0) return String(n);
  const suffixes = ['th', 'st', 'nd', 'rd'];
  const v = n % 100;
  return n + (suffixes[(v - 20) % 10] ?? suffixes[v] ?? suffixes[0]!);
}

function formatCompactFallback(amount: number): string {
  if (amount >= 1_000_000) return `${(amount / 1_000_000).toFixed(1)} million`;
  if (amount >= 1_000) return amount.toLocaleString();
  return amount.toLocaleString();
}

// ── Confidence Computation ───────────────────────────────────────────

function computeConfidence(
  funding: BriefFunding,
  voting: BriefVoting,
  oversight: BriefOversight
): number {
  let score = 0;
  let maxScore = 0;

  // Funding data available?
  maxScore += 3;
  if (funding.totalRaised !== null) score += 1;
  if (funding.contributionsSampled >= 50) score += 1;
  if (funding.topSectors.length >= 3) score += 1;

  // Voting data available?
  maxScore += 2;
  if (voting.totalVotes >= 10) score += 1;
  if (voting.billsSponsored > 0) score += 1;

  // Oversight data available?
  maxScore += 2;
  if (oversight.jurisdictionOverlapScore !== null) score += 1;
  if (oversight.topLobbyingMatches.length > 0) score += 1;

  return Math.round((score / maxScore) * 100) / 100;
}
