/**
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

/**
 * Refresh data/legislators-current.yaml and data/legislators-departed.yaml
 * from unitedstates/congress-legislators (CC0-1.0).
 *
 *   current  = upstream legislators-current.yaml + data/legislators-overlay.yaml
 *   departed = upstream legislators-historical.yaml members whose last term
 *              ended on or after the start of the previous Congress
 *
 * The departed file keeps LIS ids resolvable for senators who left mid-
 * Congress (Senate roll-call XML carries only the LIS id). No API key: these
 * are static files on GitHub Pages.
 *
 * Usage: npx tsx scripts/sync-congress-legislators.ts
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve } from 'path';
import yaml from 'js-yaml';
import {
  applyOverlay,
  previousCongressStart,
  selectDeparted,
  type OverlayEntry,
  type UpstreamLegislator,
} from '../src/lib/data/congress-legislators-sync';

const BASE = 'https://unitedstates.github.io/congress-legislators';
const CURRENT_PATH = resolve(process.cwd(), 'data/legislators-current.yaml');
const DEPARTED_PATH = resolve(process.cwd(), 'data/legislators-departed.yaml');
const OVERLAY_PATH = resolve(process.cwd(), 'data/legislators-overlay.yaml');

// Structural floors, far below the real figures (~539 current, 100 senators):
// they trip on a truncated or wrong download, not on ordinary turnover.
const MIN_CURRENT = 500;
const MIN_SENATORS = 95;

const HEADER = (source: string) =>
  `# GENERATED by scripts/sync-congress-legislators.ts — do not edit by hand.\n` +
  `# Source: ${source} (unitedstates/congress-legislators, CC0-1.0).\n` +
  `# Local additions belong in data/legislators-overlay.yaml.\n`;

async function download(file: string): Promise<UpstreamLegislator[]> {
  const response = await fetch(`${BASE}/${file}`, { signal: AbortSignal.timeout(120_000) });
  if (!response.ok) throw new Error(`${file}: HTTP ${response.status}`);
  const parsed = yaml.load(await response.text());
  if (!Array.isArray(parsed)) throw new Error(`${file}: expected a list`);
  return parsed as UpstreamLegislator[];
}

function dump(legislators: UpstreamLegislator[]): string {
  return yaml.dump(legislators, { lineWidth: -1, noRefs: true, noArrayIndent: true });
}

async function main(): Promise<void> {
  const [current, historical] = await Promise.all([
    download('legislators-current.yaml'),
    download('legislators-historical.yaml'),
  ]);

  const senators = current.filter(l => l.terms[l.terms.length - 1]?.type === 'sen').length;
  if (current.length < MIN_CURRENT || senators < MIN_SENATORS) {
    throw new Error(`Upstream looks truncated: ${current.length} members, ${senators} senators`);
  }

  const overlay = (yaml.load(readFileSync(OVERLAY_PATH, 'utf8')) ?? []) as OverlayEntry[];
  const merged = applyOverlay(current, overlay);
  if (merged.unmatched.length > 0) {
    console.warn(`Overlay entries not in the current roster: ${merged.unmatched.join(', ')}`);
  }

  const cutoff = previousCongressStart(new Date());
  const departed = selectDeparted(historical, current, cutoff);

  writeFileSync(CURRENT_PATH, HEADER('legislators-current.yaml') + dump(merged.legislators));
  writeFileSync(
    DEPARTED_PATH,
    HEADER(`legislators-historical.yaml, last term ending on/after ${cutoff}`) + dump(departed)
  );

  console.log(
    `current: ${merged.legislators.length} (${senators} senators, ${merged.applied} overlay roles)\n` +
      `departed since ${cutoff}: ${departed.length} ` +
      `(${departed.filter(l => l.id.lis).length} with LIS ids)`
  );
}

main().catch(error => {
  console.error(error);
  process.exit(1);
});
