/**
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

/**
 * Influence Cluster Types
 *
 * Types for the precomputed influence cluster data (generated by
 * scripts/compute-influence-clusters.py). The JSON is small enough
 * to check into git (~100-150KB).
 */

import type { IndustrySector } from '@/lib/fec/industry-taxonomy';

export interface InfluenceClusterData {
  generatedAt: string;
  legislatorCount: number;
  clusterCount: number;
  noisePoints: number;
  crossPartyClusters: number;
  legislators: LegislatorClusterPoint[];
  clusters: Record<number, ClusterMetadata>;
}

export interface LegislatorClusterPoint {
  bioguideId: string;
  party: 'D' | 'R' | 'I';
  chamber: 'House' | 'Senate';
  state: string;
  x: number; // UMAP coordinate
  y: number; // UMAP coordinate
  clusterId: number; // -1 = no cluster (noise)
  topSectors: Array<{ sector: IndustrySector; amount: number; pct: number }>;
}

export interface ClusterMetadata {
  memberCount: number;
  topSectors: Array<{ sector: string; meanPct: number }>;
  partyComposition: { D: number; R: number; I: number };
  isCrossParty: boolean;
}
