/**
 * Static Committee Biography Data Loader
 *
 * Loads pre-generated committee biography data for fast access.
 * This data is generated by scripts/generate-committee-biographies.mjs
 *
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

import type { CommitteeBiographicalData } from '@/lib/services/wikipedia.service';

export interface StaticCommitteeBiography {
  committeeId: string;
  committeeName: string;
  chamber: 'House' | 'Senate' | 'Joint';
  wikipedia?: {
    title: string;
    extract: string;
    extract_html?: string;
    thumbnail?: {
      source: string;
      width: number;
      height: number;
    };
    pageurl: string;
    description?: string;
  };
  wikidata?: {
    id: string;
    label: string;
    description?: string;
    wikipediaTitle?: string;
    establishedDate?: string;
    parentCommittee?: string;
  };
  jurisdiction?: string;
  history?: {
    establishedDate?: string;
    previousNames?: Array<{
      name: string;
      period: string;
      congress?: string;
    }>;
    nameChanges?: Array<{
      from: string;
      to: string;
      date: string;
      congress?: string;
    }>;
  };
  oversight?: Array<{
    agency: string;
    acronym?: string;
    wikipediaUrl?: string;
  }>;
  lastUpdated: string;
  wikipediaSuccess: boolean;
  wikidataSuccess: boolean;
}

export interface CommitteeBiographyData {
  metadata: {
    generatedAt: string;
    totalCommittees: number;
    successfulFetches: number;
    failedFetches: number;
    wikipediaSuccessRate: string;
    wikidataSuccessRate: string;
  };
  biographies: Record<string, StaticCommitteeBiography>;
}

// Import static data directly (bundled at build time)
// This will be null if the file doesn't exist yet
let cachedData: CommitteeBiographyData | null = null;

/**
 * Lazy load the committee biography data
 */
async function loadCommitteeBiographyData(): Promise<CommitteeBiographyData | null> {
  if (cachedData) return cachedData;

  try {
    // Dynamic import for the JSON data
    const data = await import('@/data/committee-biographies.json');
    cachedData = data as CommitteeBiographyData;
    return cachedData;
  } catch {
    // File doesn't exist yet (not generated), will fall back to API
    return null;
  }
}

/**
 * Get static committee biography data (synchronous)
 * Returns null if not found in static data
 * Note: You should call loadCommitteeBiographyData() first to ensure data is loaded
 */
export function getStaticCommitteeBiography(committeeId: string): StaticCommitteeBiography | null {
  if (!cachedData) {
    return null;
  }

  return cachedData.biographies[committeeId] || null;
}

/**
 * Load and get static committee biography data (async)
 */
export async function loadStaticCommitteeBiography(
  committeeId: string
): Promise<StaticCommitteeBiography | null> {
  await loadCommitteeBiographyData();
  return getStaticCommitteeBiography(committeeId);
}

/**
 * Check if static data exists for a committee ID
 */
export function hasStaticCommitteeBiography(committeeId: string): boolean {
  return getStaticCommitteeBiography(committeeId) !== null;
}

/**
 * Get metadata about the static committee biography dataset
 */
export function getCommitteeBiographyMetadata() {
  if (!cachedData) {
    getStaticCommitteeBiography(''); // Force load
  }
  return cachedData?.metadata || null;
}

/**
 * Convert static data to CommitteeBiographicalData format
 */
export function convertToCommitteeBiographicalData(
  staticData: StaticCommitteeBiography
): CommitteeBiographicalData {
  return {
    wikipedia: staticData.wikipedia,
    wikidata: staticData.wikidata,
    jurisdiction: staticData.jurisdiction,
    history: staticData.history,
    oversight: staticData.oversight,
  };
}
