/**
 * Static Biography Data Loader
 *
 * Loads pre-generated biography data for fast access.
 * This data is generated by scripts/generate-biography-data.mjs
 *
 * Copyright (c) 2019-2025 Mark Sandford
 * Licensed under the MIT License. See LICENSE and NOTICE files.
 */

export interface StaticBiography {
  bioguideId: string;
  wikipediaPageName: string;
  wikipediaSummary?: string | null;
  wikipediaHtmlSummary?: string | null;
  wikipediaImageUrl?: string | null;
  wikipediaPageUrl?: string | null;
  birthPlace?: string | null;
  education?: string[] | null;
  occupations?: string[] | null;
  spouse?: string | null;
  children?: number | null;
  awards?: string[] | null;
  wikidataDescription?: string | null;
  lastUpdated: string;
  wikipediaSuccess: boolean;
  wikidataSuccess: boolean;
}

export interface BiographyData {
  metadata: {
    generatedAt: string;
    totalRepresentatives: number;
    successfulFetches: number;
    failedFetches: number;
    wikipediaSuccessRate: string;
    wikidataSuccessRate: string;
  };
  biographies: Record<string, StaticBiography>;
}

// Import static data directly (bundled at build time)
// This will be null if the file doesn't exist yet
let cachedData: BiographyData | null = null;

/**
 * Lazy load the biography data
 */
async function loadBiographyData(): Promise<BiographyData | null> {
  if (cachedData) return cachedData;

  try {
    // Dynamic import for the JSON data
    const data = await import('@/data/representative-biographies.json');
    cachedData = data as BiographyData;
    return cachedData;
  } catch {
    // File doesn't exist yet (not generated), will fall back to API
    return null;
  }
}

/**
 * Get static biography data for a representative (synchronous)
 * Returns null if not found in static data
 * Note: You should call loadBiographyData() first to ensure data is loaded
 */
export function getStaticBiography(bioguideId: string): StaticBiography | null {
  if (!cachedData) {
    return null;
  }

  return cachedData.biographies[bioguideId] || null;
}

/**
 * Load and get static biography data (async)
 */
export async function loadStaticBiography(bioguideId: string): Promise<StaticBiography | null> {
  await loadBiographyData();
  return getStaticBiography(bioguideId);
}

/**
 * Check if static data exists for a bioguide ID
 */
export function hasStaticBiography(bioguideId: string): boolean {
  return getStaticBiography(bioguideId) !== null;
}

/**
 * Get metadata about the static biography dataset
 */
export function getBiographyMetadata() {
  if (!cachedData) {
    getStaticBiography(''); // Force load
  }
  return cachedData?.metadata || null;
}
